version: '3.8'

services:
  url_shortener:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://db:27017/url_shortener_db

  db:
    image: mongo:6.0
    container_name: mongo-db
    environment:
      MONGO_INITDB_DATABASE: url_shortener_db
    ports:
      - "27017:27017"
