version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - urlshortener-network
    volumes:
      - mongo-data:/data/db

  url_shortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener
    ports:
      - "8080:8080"
    networks:
      - urlshortener-network
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/urlshortener

networks:
  urlshortener-network:
    driver: bridge

volumes:
  mongo-data:
